# Generated by Django 2.0.5 on 2018-05-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_andy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sub_title',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
